version: '3.7'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=lambda,sns,sqs,s3
      - LAMBDA_EXECUTOR=docker
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_DOCKER_NETWORK=containers_network
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA=${LAMBDA}
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./setup.sh:/docker-entrypoint-initaws.d/setup.sh
      - ./localstack_files:/localstack_files
